export enum TagEnum {
  HAPPY = 'HAPPY',
  SAD = 'SAD',
  MOTIVATED = 'MOTIVATED',
  GRATEFUL = 'GRATEFUL',
  BLESSED = 'BLESSED',
  ANXIOUS = 'ANXIOUS',
  RELAXED = 'RELAXED',
  PRODUCTIVE = 'PRODUCTIVE',
  REFLECTIVE = 'REFLECTIVE',
}
